---
- name: Become block
  block:
    - name: Install required packages
      apt:
        name: '{{ hashicorp_packages_base | union(hashicorp_packages_additional) | unique }}'
        state: present
        update_cache: true
      register: installed_package
      until: installed_package is succeeded

    - name: Add Hashicorp GPG key
      apt_key:
        url: '{{ hashicorp_gpg }}'
      register: installed_package
      until: installed_package is succeeded

    - name: Add Hashicorp repository
      apt_repository:
        repo: '{{ hashicorp_repo }}'
        validate_certs: true
  become: true
