---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Gather the package facts
      package_facts:
        manager: auto

    - name: Populate service facts
      service_facts:
